### ISSUE TITLE
Add tails smoothing

### ISSUE THREAD

**Issue by jngadiub** [Diboson3D/cmgtools-lite#38]

**Comment by daniSchaefer** [comment]
a few thoughts to this:
1) i had worked on a version of the tail smoothing for the 2D fit which can be found here: https://github.com/daniSchaefer/cmgtools-lite/blob/qstarStat/VVResonances/scripts/vvMake2DTemplateWithKernels.py#L66, using the mJJ dijet fit function to smooth the spectrum per bin which gives good shapes for the Mjj direction (simple exponential underestimated the tails)
i never made a pull request for this since the smoothing of the tails in mjj distorts the conditional mjet, resulting in weird shapes after the convolution step (see for example attached figure)
[ProjInMVVBin140overMjet.pdf](https://github.com/Diboson3D/cmgtools-lite/files/1481911/ProjInMVVBin140overMjet.pdf) 
2) the way we are doing the convolution now i.e. the conditional templates are now P(m_jet | mJJ) and not the other way around. so it is not so straightforward here how to implement the tail-smoothing. 
-> perhaps implement on final TH3 after the convolution step, but not clear if this messes up the other two dimensions too much

**Comment by jngadiub** [comment]
I think that it is worth to try to merge what you already have in the P(mjet|mjj) 2D template maker

https://github.com/Diboson3D/cmgtools-lite/blob/3DVVstat/VVResonances/scripts/vvMake2DTemplateWithKernels.py

Just remember that now you have mjj on the y-axis (instead of the x-axis as before).
I am not sure if we should implement it for the 1D mjj template too.

I guess we should just try all these things and see how the limits change. One can do these tests with herwig only.
